### ISSUE TITLE
Error on Installing - Permission Denied (Windows 10 Pro, 20H1)

### ISSUE THREAD

**Issue by RoyiAvital** [heetbeet/juliawin#33] opened 2020-12-09 09:40 UTC
On installing I get the following errors:

![image](https://user-images.githubusercontent.com/7347975/101612309-2e451100-3a13-11eb-8615-023fbdc488ef.png)

![image](https://user-images.githubusercontent.com/7347975/101612272-22f1e580-3a13-11eb-9381-49032f175980.png)

They seem to be related to some operation of unlinking and not having permissions.
I run the `bat` file as instructed.

Has anyone experienced it? Any solution?

**Comment by heetbeet** [comment] 2020-12-09 14:46
The `unlink` is triggered through:
`temp_cleanup_purge` -> `rm` -> `unlink` 
https://github.com/JuliaLang/julia/blob/bc94c501b6d5e1330e5146dac720df373add8cdc/base/file.jl#L272

Unlink gets called on all files and non-directories during a call to `rm`. Unlink is not specifically for symlinks and is the catch-all for deleting both links and files.  (The same is true for Python's unlink implementation: https://docs.python.org/3/library/os.html#os.unlink )

So the problem seems to be that some temporary file during the installation/compilation of ArgParse cannot be deleted. This is strange indeed.

The specific line that causes the error is `ArgParse.jl` line 14, on my end this is `using TextWrap`.
At which part of the process is your installation broken? Can you open julia.exe?

**Comment by heetbeet** [comment] 2020-12-09 14:51
Would it be possible to download the complete release from https://github.com/heetbeet/juliawin/releases/tag/v0.2.0 and install/extract it on your system. Then you can report on what happens when you do:
`using TextWrap`

or in package manager:
`remove ArgParse`
`add ArgParse`

**Comment by heetbeet** [comment] 2020-12-09 14:56
Cause the point at which this error occurs you already have a working Julia, but that Julia doesn't seem to be able to install ArgParse. What is more strange is to get to this position, a lot of temporary files would have been written to %temp% already. But maybe this is the first instance in the pipeline where a file needed to be deleted from temp.

From earlier conversations I know that you have already tried writing and then deleting a file to %temp%.

**Comment by RoyiAvital** [comment] 2020-12-09 18:37
My thoughts are:

 * Could it be Windows Defender?
 * Could it be something runs in parallel so one thread / process tries to delete a file accessed by other thread / process?

Is there a way to get the path / file name it tries to delete?

**Comment by heetbeet** [comment] 2020-12-10 08:16
Edit the file `packages\julia\share\julia\base\file.jl`:
```
function unlink(p::AbstractString)
    println(p)                                       #<- add this line to print each file that gets unlinked
    err = ccall(:jl_fs_unlink, Int32, (Cstring,), p)
    uv_error("unlink", err)
    nothing
end
```

**Comment by heetbeet** [comment] 2020-12-10 09:16
Antivirus or some strange privileges would be my best bet. I think some parallel race condition is unlikely since I haven't seen that error somewhere else regarding ArgParse.

**Comment by RoyiAvital** [comment] 2020-12-10 10:25
What if I want to see the file name only in case of error?

**Comment by heetbeet** [comment] 2020-12-10 10:46
Then you can wrap the function's code in a try catch. But, this is only for experimentation and getting your hand dirty in finding the locked file, I don't recommend to go edit this in on a usable Julia installation (unless you want to properly add the filename reporting to the error mechanism and lodge an issue over at the official Julia repo). As such, just print every file that tries to be deleted and the last one on the screen prior to the error would be the culprit you are looking for.

**Comment by RoyiAvital** [comment] 2020-12-10 21:05
OK,
I tried a Portable Julia based on the official ZIP and defining `JULIA_DEPOT_PATH` as you instructed me.

Then I tried:

```
julia> using Pkg
julia> Pkg.add("ArgParse")
```

I got:

![image](https://user-images.githubusercontent.com/7347975/101829711-1ae19500-3b3c-11eb-88e0-6c203129a09b.png)

Which means it worked!

Makes things more interesting.

**Comment by heetbeet** [comment] 2020-12-11 07:57
One further test you can do is the following:
Extract the 1.2 Gb version somewhere ( https://github.com/heetbeet/juliawin/releases/tag/v0.2.0 )
Replace the `packages\julia` folder with the portable julia version ( https://julialang-s3.julialang.org/bin/winnt/x64/1.5/julia-1.5.3-win64.zip )

And see if Julia can do:
```
using Pkg
Pkg.rm("ArgParse")
Pkg.add("ArgParse")
```

**Comment by RoyiAvital** [comment] 2020-12-11 08:41
The deletion and adding worked:

![image](https://user-images.githubusercontent.com/7347975/101881591-4f396d80-3b9d-11eb-8dc2-d690de5b9ea9.png)

Using failed.

This is with the _Portable_ Julia. So I think it is not something specifically to `JuliaWin`.

**Comment by heetbeet** [comment] 2020-12-11 10:11
Okay, I think the problem is then quite deeper. And probably more specific to your system. Maybe the general Slack help or the Julia discourse channel https://discourse.julialang.org/ will be able to help with this.

**Comment by heetbeet** [comment] 2021-01-12 21:54
I also got one of these recently :(
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Run with "/h" for help
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Unofficial installer for Juliawin
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    162      0  0:00:01 --:--:--  0:00:01  3446
100 24284  100 24284    0     0  24284      0  0:00:01 --:--:--  0:00:01 24284
() Got Julia link as https://julialang-s3.julialang.org/bin/winnt/x64/1.5/julia-1.5.3-win64.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 67.5M  100 67.5M    0     0  2561k      0  0:00:27  0:00:27 --:--:-- 2511k
() Extracting C:\Users\simon\AppData\Local\Temp\julia-bootstrap-download-104392913\julia-1.5.3-win64.exe into "C:\Users\simon\devel\juliawin\packages\julia"
 Installing known registries into `C:\Users\simon\devel\juliawin\userdata\.julia`
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
      Added registry `General` to `C:\Users\simon\devel\juliawin\userdata\.julia\registries\General`
  Resolving package versions...
  Installed CodeTracking ─────── v1.0.5
  Installed Requires ─────────── v1.1.2
  Installed OrderedCollections ─ v1.3.2
  Installed JuliaInterpreter ─── v0.8.8
  Installed LoweredCodeUtils ─── v1.2.7
  Installed Revise ───────────── v3.1.11
Updating `C:\Users\simon\devel\juliawin\userdata\.julia\environments\v1.5\Project.toml`
  [295af30f] + Revise v3.1.11
Updating `C:\Users\simon\devel\juliawin\userdata\.julia\environments\v1.5\Manifest.toml`
  [da1fd8a2] + CodeTracking v1.0.5
  [aa1ae85d] + JuliaInterpreter v0.8.8
  [6f1432cf] + LoweredCodeUtils v1.2.7
  [bac558e1] + OrderedCollections v1.3.2
  [ae029012] + Requires v1.1.2
  [295af30f] + Revise v3.1.11
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
ERROR: LoadError: IOError: unlink: permission denied (EACCES)
Stacktrace:
 [1] uv_error at .\libuv.jl:97 [inlined]
 [2] unlink(::String) at .\file.jl:918
 [3] rm(::String; force::Bool, recursive::Bool) at .\file.jl:268
 [4] compilecache(::Base.PkgId, ::String) at .\loading.jl:1300
 [5] _require(::Base.PkgId) at .\loading.jl:1030
 [6] require(::Base.PkgId) at .\loading.jl:928
 [7] require(::Module, ::Symbol) at .\loading.jl:923
 [8] include(::Function, ::Module, ::String) at .\Base.jl:380
 [9] include(::Module, ::String) at .\Base.jl:368
 [10] top-level scope at none:2
 [11] eval at .\boot.jl:331 [inlined]
 [12] eval(::Expr) at .\client.jl:467
 [13] top-level scope at .\none:3
in expression starting at C:\Users\simon\devel\juliawin\userdata\.julia\packages\Revise\moD4B\src\Revise.jl:12
caused by [exception 1]
IOError: unlink: permission denied (EACCES)
Stacktrace:
 [1] uv_error at .\libuv.jl:97 [inlined]
 [2] unlink(::String) at .\file.jl:918
 [3] rm(::String; force::Bool, recursive::Bool) at .\file.jl:268
 [4] rename(::String, ::String; force::Bool) at .\file.jl:928
 [5] compilecache(::Base.PkgId, ::String) at .\loading.jl:1296
 [6] _require(::Base.PkgId) at .\loading.jl:1030
 [7] require(::Base.PkgId) at .\loading.jl:928
 [8] require(::Module, ::Symbol) at .\loading.jl:923
 [9] include(::Function, ::Module, ::String) at .\Base.jl:380
 [10] include(::Module, ::String) at .\Base.jl:368
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:331 [inlined]
 [13] eval(::Expr) at .\client.jl:467
 [14] top-level scope at .\none:3
┌ Warning: temp cleanup
│   exception =
│    IOError: unlink: permission denied (EACCES)
│    Stacktrace:
│     [1] uv_error at .\libuv.jl:97 [inlined]
│     [2] unlink(::String) at .\file.jl:918
│     [3] rm(::String; force::Bool, recursive::Bool) at .\file.jl:268
│     [4] temp_cleanup_purge(::Bool) at .\file.jl:514
│     [5] temp_cleanup_purge() at .\file.jl:507
│     [6] _atexit() at .\initdefs.jl:316
│     [7] exit at .\initdefs.jl:28 [inlined]
│     [8] _start() at .\client.jl:509
└ @ Base.Filesystem file.jl:518
ERROR: LoadError: LoadError: Failed to precompile Revise [295af30f-e4ad-537b-8983-00126c2a3abe] to C:\Users\simon\devel\juliawin\userdata\.julia\compiled\v1.5\Revise\M1Qoh_rMyo1.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1305
 [3] _require(::Base.PkgId) at .\loading.jl:1030
 [4] require(::Base.PkgId) at .\loading.jl:928
 [5] require(::Module, ::Symbol) at .\loading.jl:923
in expression starting at C:\Users\simon\devel\juliawin\userdata\.julia\config\juliawinconfig.jl:6
in expression starting at C:\Users\simon\devel\juliawin\internals\juliawin_cli.jl:6
caused by [exception 1]
ArgumentError: Package Revise not found in current path:
- Run `import Pkg; Pkg.add("Revise")` to install the Revise package.

Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:893

() End of Juliawin installation
Press any key to continue . . .
```

**Comment by RoyiAvital** [comment] 2021-01-15 13:08
Does it give you any idea of what's happening?

**Comment by heetbeet** [comment] 2021-01-16 13:55
No, not at all. I tried installing to another location and it then worked. Will have to investigate when I have some free time to spare

**Comment by heetbeet** [comment] 2021-02-18 13:49
This might be related. Hopefully this is only a 1.5.3 problem and not a 1.6 problem:
https://github.com/JuliaLang/julia/issues/38411

**Comment by heetbeet** [comment] 2021-06-15 21:34
It's quite difficult to know about all the installation issues that can occur on other people's machines. If further problems persists, then we can reopen this issue, for now, I'm gonna close it. If Anyone struggles to use the thin installer, I've added offline installers for these type of problem:

https://github.com/heetbeet/juliawin/releases

**Closed as completed by heetbeet** 2021-06-15 21:34 UTC
